### ISSUE TITLE
[Error] yarn add umi-plugin-md

### ISSUE THREAD

**Issue by xiaohuoni** [chiaweilee/umi-plugin-md#1]
```sh
error /Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md: Command failed.
Exit code: 1
Command: node ./scripts/patch.js
Arguments: 
Directory: /Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md
Output:
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/node_modules/umi-build-dev/lib/routes/getRouteConfigFromDir.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object._default [as default] (/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/lib/patch.js:15:20)
    at Object.<anonymous> (/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/scripts/patch.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by xiaohuoni** [comment]
try again
```sh
success Saved lockfile.
$ node ./scripts/patch.js
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../lib/patch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/xiaohuoni/umi-plugin-md/scripts/patch.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by chiaweilee** [comment]
> ```shell
> error /Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md: Command failed.
> Exit code: 1
> Command: node ./scripts/patch.js
> Arguments: 
> Directory: /Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md
> Output:
> fs.js:115
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, open '/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/node_modules/umi-build-dev/lib/routes/getRouteConfigFromDir.js'
>     at Object.openSync (fs.js:436:3)
>     at Object.readFileSync (fs.js:341:35)
>     at Object._default [as default] (/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/lib/patch.js:15:20)
>     at Object.<anonymous> (/Users/xiaohuoni/Desktop/docs/node_modules/umi-plugin-md/scripts/patch.js:1:94)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
> ```

Indeed, It is a bug which I am gonna to do next..
`abandon 'patch.js', gonna to be graceful. addrouterimport / modifyroutes`

It happened when umi-plugin-md install before umi installed.
I'll retry to fix it this week, thanks!
